apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ronlghhs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-ronlghhs:9f0b80f531001083647a848cf9af4a0d1ad679d0@sha256:6ff60c09d923bf642cd569a87680f97b15e83f1c719d66068d592a039f53a4d8
          name: container-image
